backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "src/assets/imgs/uploads"

collections:
  - name: "update"
    label: "Updates"
    folder: "src/data/updates"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: hidden, default: "update"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label`: "Body", name: "body", widget: "markdown"}

  - name: "item"
    label: "Items"
    folder: "src/data/items"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: hidden, default: "product"}
      - {label: "Title", name: "title", widget: "string"}
