backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: /uploads

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: src/content/posts
    create: true
    slug: '{{slug}}'
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Rating (scale of 1-5), name: rating, widget: number}
      - {label: Body, name: body, widget: markdown}
